global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'express-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:3000']

  - job_name: 'django-adminpanel'
    static_configs:
      - targets: ['django:8000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

